

[postgres]

host = "localhost"
port = 5432
user = "postgres"
password = "qwerty"


[sql]

prepare_database = """    
    DROP TABLE IF EXISTS comments;
    CREATE TABLE comments (user_id integer, description text, path text);

    INSERT INTO comments (user_id, description, path) VALUES ( 1, md5(random()::text), '0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 2, md5(random()::text), '0001.0001.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 2, md5(random()::text), '0001.0001.0001.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 1, md5(random()::text), '0001.0001.0001.0002');
    INSERT INTO comments (user_id, description, path) VALUES ( 5, md5(random()::text), '0001.0001.0001.0003');
    INSERT INTO comments (user_id, description, path) VALUES ( 6, md5(random()::text), '0001.0002');
    INSERT INTO comments (user_id, description, path) VALUES ( 6, md5(random()::text), '0001.0002.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 6, md5(random()::text), '0001.0003');
    INSERT INTO comments (user_id, description, path) VALUES ( 8, md5(random()::text), '0001.0003.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 9, md5(random()::text), '0001.0003.0002');
    INSERT INTO comments (user_id, description, path) VALUES ( 11, md5(random()::text), '0001.0003.0002.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 2, md5(random()::text), '0001.0003.0002.0002');

    INSERT INTO comments (user_id, description, path) VALUES ( 5, md5(random()::text), '0001.0003.0002.0003');
    INSERT INTO comments (user_id, description, path) VALUES ( 7, md5(random()::text), '0001.0003.0002.0002.0001');
    INSERT INTO comments (user_id, description, path) VALUES ( 20, md5(random()::text), '0001.0003.0002.0002.0002');
    INSERT INTO comments (user_id, description, path) VALUES ( 31, md5(random()::text), '0001.0003.0002.0002.0003');
    INSERT INTO comments (user_id, description, path) VALUES ( 22, md5(random()::text), '0001.0003.0002.0002.0004');
    INSERT INTO comments (user_id, description, path) VALUES ( 34, md5(random()::text), '0001.0003.0002.0002.0005');
    INSERT INTO comments (user_id, description, path) VALUES ( 22, md5(random()::text), '0001.0003.0002.0002.0006');
"""

find_all = """        
    with recursive coms( id, parent_id, path ) as (
        SELECT
            0 as id,
            0 as parent_id,
            path
        FROM
            public.comments
        where
            path = $1
        union
        SELECT
            coms.id + (ROW_NUMBER () OVER (ORDER BY coms.id))::integer + 1 as id,
            coms.id,
            comm.path
        FROM
            public.comments as comm,
            coms
        where
            comm.path like ( coms.path || '.____' )
    )
    SELECT * from coms;
"""